### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by enhany** [youngwanLEE/CenterMask#15]
I'm trying to train with default config (coco dataset):

python -m torch.distributed.launch --nproc_per_node=1 tools/train_net.py --config-file "configs/centermask/centermask_V_19_eSE_FPN_lite_res600_ms_bs16_4x.yaml"

and I'm getting error right after start training:

```
2020-01-31 10:25:50,812 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 189, in <module>
    main()
  File "tools/train_net.py", line 182, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 88, in train
    arguments,
  File "e:\files\tmp\centermask\maskrcnn_benchmark\engine\trainer.py", line 71, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "d:\env\ce\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "d:\env\ce\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "d:\env\ce\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "d:\env\ce\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "d:\env\ce\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "d:\env\ce\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "d:\env\ce\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "d:\env\ce\lib\site-packages\torch\utils\data\dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "e:\files\tmp\centermask\maskrcnn_benchmark\data\datasets\coco.py", line 91, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "e:\files\tmp\centermask\maskrcnn_benchmark\structures\bounding_box.py", line 224, in clip_to_image
    return self[keep]
  File "e:\files\tmp\centermask\maskrcnn_benchmark\structures\bounding_box.py", line 209, in __getitem__
    bbox.add_field(k, v[item])
  File "e:\files\tmp\centermask\maskrcnn_benchmark\structures\segmentation_mask.py", line 513, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "e:\files\tmp\centermask\maskrcnn_benchmark\structures\segmentation_mask.py", line 422, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range
```

**Comment by youngwanLEE** [comment]
@enhany 
In my side, this error did not occur.

What pytorch and torchvision version are you using?

Why did you use `--nproc_per_node=1` ?

When you want to use single GPU, you don't need to use
 `torch.distributed.launch --nproc_per_node=$NGPUS`

And If you want to train using sinlge GPU, you have to decrease `SOLVER.IMS_PER_BATCH`

**Comment by enhany** [comment]
@youngwanLEE 
pytorch 1.4.0
torchvision 0.5.0

> When you want to use single GPU, you don't need to use

Thank you. I change it to:
python tools/train_net.py --config-file "configs/centermask/centermask_V_39_eSE_FPN_lite_res600_ms_bs16_4x.yaml" SOLVER.IMS_PER_BATCH 1

But error persists.

**Comment by youngwanLEE** [comment]
@enhany 

I guess the problem maybe torchvision.

How about downgrade the version of pytorch and torchvision to 1.1.0 and 0.3.0, respectively?

**Comment by enhany** [comment]
@youngwanLEE 

yes, pytorch 1.1.0, torchvision 0.3.0 works.
