### ISSUE TITLE
Its really difficult to train out a good mAP when training on my own dataset

### ISSUE THREAD

**Issue by JerryIndus** [youngwanLEE/CenterMask#20]
### Problem Summary
Firstly, I trained on standard COCO dataset used in this paper, and got a good mAP. Secondly, I prepared my own dataset according to COCO format and named them as "train2014"、 "val2014"、 "instances_train2014.json"、"instances_val2014.json". Thirdly, since my own dataset contains only one category --'building', so I changed '_C.MODEL.ROI_BOX_HEAD.NUM_CLASSES'、'_C.MODEL. FCOS.NUM_CLASSES'、'_C.MODEL.RETINANET.NUM_CLASSES' in defaults.py from 81 to 2. And then I trained on my own dataset. But got a bad mAP. It is worth mentioning that I have already visualized my own dataset, and my own dataset performed good in maskrcnn. Thus, I want to ask you if the centermask can be used for other datasets, or if I need to modify any other information when training with my own dataset. [I noticed that there is an issue in FCOS which is similar with this problem: https://github.com/tianzhi0549/FCOS/issues/132, but the issue is also not resolved.]
### Environment
GPU: 4 titan xp (12GB)
Versions of relevant libraries:
[pip] numpy==1.16.0
[pip] torch==1.0.0.dev20190328
[pip] torchvision==0.2.2
[conda] pytorch-nightly           1.0.0.dev20190328 py3.7_cuda9.0.176_cudnn7.4.2_0    <unknown>
[conda] torchvision               0.2.2                    pypi_0    pypi
        Pillow (6.2.1)
### configs
![捕获](https://user-images.githubusercontent.com/46989078/74343324-daaf6a00-4de5-11ea-8fdd-0081ff5ea886.PNG)
### loss
![log_result](https://user-images.githubusercontent.com/46989078/74337568-7edfe380-4ddb-11ea-9391-9337990b394c.png)
### AP and AR
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.004
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.008
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.018
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.019
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.091
Maximum f-measures for classes:
[0.04064810445178543]
Score thresholds for classes (used in demos for visualization purposes):
[0.016668733209371567]
Loading and preparing results...
DONE (t=0.19s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=13.13s).
Accumulating evaluation results...
DONE (t=0.23s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.011
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.011
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.011
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.086
Maximum f-measures for classes:
[0.02170795306388527]
Score thresholds for classes (used in demos for visualization purposes):
[0.33201679587364197]
2020-01-17 04:11:24,843 maskrcnn_benchmark.inference INFO: OrderedDict([('bbox', OrderedDict([('AP', 0.0010722595928040015), ('AP50', 0.003614397825546365), ('AP75', 0.0003211566688604318), ('APs', 0.0016450320259484557), ('APm', 0.0011716715215730757), ('APl', 0.007575648306486348)])), ('segm', OrderedDict([('AP', 0.0027830979629441433), ('AP50', 0.005436005785051814), ('AP75', 0.002610742186121677), ('APs', 0.00037027883278494873), ('APm', 0.002340194956846525), ('APl', 0.01333755135821637)]))])

**Comment by youngwanLEE** [comment]
@JerryIndus 
Did you visualize the result using [demo.py](https://github.com/youngwanLEE/CenterMask/blob/master/demo/centermask_demo.py)?

I wonder the qualitative result is good or not.

If the visualized result is good, the problem is results from evaluation step.

**Comment by JerryIndus** [comment]
@youngwanLEE 
Thank you very much for your reply. But I'm sorry, due to the impact of my country's epidemic （NCP）, I can't remote the server now, so maybe it will take some time to visualize the results with demo.py. Once I gain the visualization result, I will immediately comment here. Thanks!

**Comment by JerryIndus** [comment]
@youngwanLEE 
Excuse me, I have already visualized the results using demo.py, and you can see some of the results in the figure below.
![result](https://user-images.githubusercontent.com/46989078/74606302-4c4f2700-510a-11ea-9295-f4c6175138eb.PNG)
Some of the test results have error detections and missed detections, but I think the AP and AR values should not be so bad, that's so strange...
At the same time, I noticed a phenomenon: when the program runs to some images, it comes an IndexError:
> val_206 processing...
val_206	inference time: 0.16s
file 83
val_207 processing...
val_207	inference time: 0.15s
file 84
val_208 processing...
Traceback (most recent call last):
  File "./demo/centermask_demo.py", line 168, in <module>
    main()
  File "./demo/centermask_demo.py", line 158, in main
    composite = coco_demo.run_on_opencv_image(img)
  File "/media/wt/DATA/centermask/CenterMask/demo/predictor.py", line 224, in run_on_opencv_image
    predictions = self.compute_prediction(image)
  File "/media/wt/DATA/centermask/CenterMask/demo/predictor.py", line 262, in compute_prediction
    prediction = predictions[0]
IndexError: list index out of range

I debug it using one specified image, and you can see when running compute_prediction() function[predictor.py(262)], the predictions is none, and then it led to IndexError. I don't know how to resolve it and whether this problem causes the bad AP or not?
![2](https://user-images.githubusercontent.com/46989078/74606355-c67fab80-510a-11ea-9d94-f303030edda1.PNG)
These are some problems and gains I have encountered at present, looking forward to your reply.Thank you very much!

**Comment by youngwanLEE** [comment]
@JerryIndus 
The qualitative results look good. 

I guess the problem results from a custom dataset setting or evaluator. 

The above problem is occurs when there are no detection results. 

You can simply handle by adding `try` ~ `except` .

**Comment by JerryIndus** [comment]
@youngwanLEE 
I'm not very understanding the sentence you said: “I guess the problem results from a custom dataset setting or evaluator.” , and could you explain it in more detail? I still don't have a clue.

**Comment by JerryIndus** [comment]
@youngwanLEE 
I debugged again in the two days, and found that the test data can be read and print correctly.  And there is no problem with  evaluator. But the predictions obtained by [demo.py](https://github.com/youngwanLEE/CenterMask/blob/master/demo/centermask_demo.py)->[predictor.py](https://github.com/youngwanLEE/CenterMask/blob/master/demo/predictor.py)->compute_prediction() is different from  the predictions obtained by [inference.py](https://github.com/youngwanLEE/CenterMask/blob/bcf4d84e09ce79201c2f2aced77a0fcc18246a13/maskrcnn_benchmark/engine/inference.py)->compute_on_dataset(). Maybe this can explain why use [demo.py](https://github.com/youngwanLEE/CenterMask/blob/master/demo/centermask_demo.py) can gain a good visualized results, but the AP is bad. But I really don't know what caused this phenomenon. After all, they call the same functions and the same weight. So I still want to ask you. Looking forward to your reply.Thank you very much!
illustrate in more detail:
![2020-02-27 20-38-49屏幕截图](https://user-images.githubusercontent.com/46989078/75446076-a9b46500-59a1-11ea-96a2-3530f4e8e42d.png)
By the way, the problem:list index out of range when running [demo.py](https://github.com/youngwanLEE/CenterMask/blob/master/demo/centermask_demo.py) has already resolved by using try~except, Thanks for the tip.

**Comment by hakillha** [comment]
I ran into a very similar situation. I tried running centermask on my own dataset following steps in the maskrcnn-benchmark to modify the # of classes and trimm the pretrained file. It can train just fine but whenever I tried to run inference or evaluation the code always crashed returning cuda errors for a certain image. And I also tried simply using try/except clause to ignore the error but the model just seemed broken hereafter and it simply didn't work.

**Comment by TengFeiHan0** [comment]
@JerryIndus I got the same problem with you. All APs are smaller than 0.01. I was wondering some wrong operations have been made.  Now I see your post and plan to retrain my model again.

**Comment by Auth0rM0rgan** [comment]
Hey all, 

I'm facing this error when I'm trying to train the centermask from scratch. any idea?

my command line:
  
`python -m torch.distributed.launch --nproc_per_node=1 tools/train_net.py --config-file "configs/centermask/centermask_V_19_eSE_FPN_lite_res600_ms_bs16_4x.yaml"`

Everything goes fine until here
`loading annotations into memory...
Done (t=9.23s)
creating index...
index created!
loading annotations into memory...
Done (t=0.27s)
creating index...
index created!
2020-03-17 17:12:30,920 maskrcnn_benchmark.trainer INFO: Start training` 

After that I'm getting this error: `IndexError: list index out of range`

Thanks!

**Comment by TengFeiHan0** [comment]
@Auth0rM0rgan In my opinion, you had better train your model on multiple GPUs(at least 2 GPUs).  As for your error, would you mind providing more info about this? we couldn't imply what you have met only depending on a single line.

**Comment by Auth0rM0rgan** [comment]
@TengFeiHan0 I have tried with 2 GPUs as well but still getting the same error. Here is the log file  [log.txt](https://github.com/youngwanLEE/CenterMask/files/4348956/log.txt) generated by the model and then I'm getting this error:
 
```
Traceback (most recent call last):
  File "tools/train_net.py", line 189, in <module>
    main()
  File "tools/train_net.py", line 182, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 88, in train
    arguments,
  File "/home/CenterMask/maskrcnn_benchmark/engine/trainer.py", line 71, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/CenterMask/maskrcnn_benchmark/data/datasets/coco.py", line 91, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "/home/CenterMask/maskrcnn_benchmark/structures/bounding_box.py", line 224, in clip_to_image
    return self[keep]
  File "/home/CenterMask/maskrcnn_benchmark/structures/bounding_box.py", line 209, in __getitem__
    bbox.add_field(k, v[item])
  File "/home/CenterMask/maskrcnn_benchmark/structures/segmentation_mask.py", line 513, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "/home/CenterMask/maskrcnn_benchmark/structures/segmentation_mask.py", line 422, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range
```
Thanks

**Comment by TengFeiHan0** [comment]
@Auth0rM0rgan  I remember that I have seen the same error, please check this [issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/1080). Anyway, I guess your PyTorch version is not the same as the author suggested. If I'm right, please create a virtual envs to install maskrcnn-benchmark again.

**Comment by TengFeiHan0** [comment]
@Auth0rM0rgan after checked your log, I find that your pytorch version is 1.4.0 and torchvision is also the latest. please follow these [instructions](https://github.com/youngwanLEE/CenterMask/blob/master/INSTALL.md) to set up a new virtual envs. by the way, when executing this line" `conda install -c pytorch torchvision=0.2.1 cudatoolkit=9.0`", please ensure one thing that your current Cuda version does not conflict with this Cudatoolkit.

**Comment by sadik1111** [comment]
> Problem Summary
> Firstly, I trained on standard COCO dataset used in this paper, and got a good mAP. Secondly, I prepared my own dataset according to COCO format and named them as "train2014"、 "val2014"、 "instances_train2014.json"、"instances_val2014.json". Thirdly, since my own dataset contains only one category --'building', so I changed '_C.MODEL.ROI_BOX_HEAD.NUM_CLASSES'、'_C.MODEL. FCOS.NUM_CLASSES'、'_C.MODEL.RETINANET.NUM_CLASSES' in defaults.py from 81 to 2. And then I trained on my own dataset. But got a bad mAP. It is worth mentioning that I have already visualized my own dataset, and my own dataset performed good in maskrcnn. Thus, I want to ask you if the centermask can be used for other datasets, or if I need to modify any other information when training with my own dataset. [I noticed that there is an issue in FCOS which is similar with this problem: https://github.com/tianzhi0549/FCOS/issues/132, but the issue is also not resolved.]
> Environment
> GPU: 4 titan xp (12GB)
> Versions of relevant libraries:
> [pip] numpy==1.16.0
> [pip] torch==1.0.0.dev20190328
> [pip] torchvision==0.2.2
> [conda] pytorch-nightly           1.0.0.dev20190328 py3.7_cuda9.0.176_cudnn7.4.2_0    
> [conda] torchvision               0.2.2                    pypi_0    pypi
> Pillow (6.2.1)
> configs
> 
> loss
> 
> AP and AR
> 
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
> Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.004
> Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.001
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.008
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.003
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.013
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.018
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.013
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.019
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.091
> Maximum f-measures for classes:
> [0.04064810445178543]
> Score thresholds for classes (used in demos for visualization purposes):
> [0.016668733209371567]
> Loading and preparing results...
> DONE (t=0.19s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type segm
> DONE (t=13.13s).
> Accumulating evaluation results...
> DONE (t=0.23s).
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.003
> Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.005
> Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.003
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.002
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.013
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.003
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.011
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.013
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.011
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.011
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.086
> Maximum f-measures for classes:
> [0.02170795306388527]
> Score thresholds for classes (used in demos for visualization purposes):
> [0.33201679587364197]
> 2020-01-17 04:11:24,843 maskrcnn_benchmark.inference INFO: OrderedDict([('bbox', OrderedDict([('AP', 0.0010722595928040015), ('AP50', 0.003614397825546365), ('AP75', 0.0003211566688604318), ('APs', 0.0016450320259484557), ('APm', 0.0011716715215730757), ('APl', 0.007575648306486348)])), ('segm', OrderedDict([('AP', 0.0027830979629441433), ('AP50', 0.005436005785051814), ('AP75', 0.002610742186121677), ('APs', 0.00037027883278494873), ('APm', 0.002340194956846525), ('APl', 0.01333755135821637)]))])

Is it convenient for you to leave a email? I would like to ask how you made the coco format dataset.I made and converted it with labelme, which can run in other models, but I don't know why there is class problem `Key DATALOADER with value <class 'NoneType'> is not a valid type` in this model

**Comment by sadik1111** [comment]
@youngwanLEE I have change all `num_of_class` in defaults.py to my "num_of_class" in my dataset. But my train loss is so bad, and there are so many `nan`. The ` loss_cls` is so high, and it is around 20 without changes.My `batch size` is 16, and the LR is 0.01. Is there anything I haven't corrected correctly? Thanks for any help!

### Config
`MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN_ONLY: True
  FCOS_ON: True
  FCOS_MASK: True
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  MASK_ON: True
  MASKIOU_ON: True
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
    INFERENCE_TH: 0.03
  ROI_HEADS:
    USE_FPN: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNSpatialAttentionFeatureExtractor"
    LEVEL_MAP_FUNCTION: "CenterMaskLevelMapFunc"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
DATASETS:
  TRAIN: ("coco_2017_train", )
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 800
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (6000, 8000)
  MAX_ITER: 9000
  IMS_PER_BATCH: 26 
  WARMUP_METHOD: "constant"
OUTPUT_DIR : 'checkpoints/CenterMask-R-101-FPN-1x'`

### log
2020-04-13 03:28:58,093 maskrcnn_benchmark.trainer INFO: Start training
2020-04-13 03:29:31,324 maskrcnn_benchmark.trainer INFO: eta: 4:08:40  iter: 20  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.7949 (17.9550)  loss_mask: 0.6925 (1.9894)  loss_maskiou: 0.1683 (9.0416)  loss_reg: nan (nan)  time: 1.4917 (1.6615)  data: 0.0193 (0.0550)  lr: 0.003333  max mem: 12016
2020-04-13 03:30:01,571 maskrcnn_benchmark.trainer INFO: eta: 3:56:58  iter: 40  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.7492 (19.3572)  loss_mask: 0.6835 (1.3374)  loss_maskiou: 0.0212 (4.5379)  loss_reg: nan (nan)  time: 1.5237 (1.5869)  data: 0.0185 (0.0373)  lr: 0.003333  max mem: 12016
2020-04-13 03:30:32,846 maskrcnn_benchmark.trainer INFO: eta: 3:55:18  iter: 60  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8152 (19.8398)  loss_mask: 0.6828 (1.1191)  loss_maskiou: 0.0102 (3.0335)  loss_reg: nan (nan)  time: 1.5796 (1.5792)  data: 0.0193 (0.0314)  lr: 0.003333  max mem: 12016
2020-04-13 03:31:04,427 maskrcnn_benchmark.trainer INFO: eta: 3:54:46  iter: 80  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8607 (20.0847)  loss_mask: 0.6839 (1.0099)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5764 (1.5792)  data: 0.0189 (0.0286)  lr: 0.003333  max mem: 12016
2020-04-13 03:31:35,464 maskrcnn_benchmark.trainer INFO: eta: 3:53:25  iter: 100  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.7950 (20.2315)  loss_mask: 0.6857 (0.9452)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5660 (1.5737)  data: 0.0198 (0.0269)  lr: 0.003333  max mem: 12016
2020-04-13 03:32:06,725 maskrcnn_benchmark.trainer INFO: eta: 3:52:38  iter: 120  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8000 (20.3229)  loss_mask: 0.6805 (0.9013)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5790 (1.5719)  data: 0.0206 (0.0260)  lr: 0.003333  max mem: 12016
2020-04-13 03:32:38,183 maskrcnn_benchmark.trainer INFO: eta: 3:52:08  iter: 140  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8168 (20.3925)  loss_mask: 0.6816 (0.8701)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5704 (1.5721)  data: 0.0204 (0.0253)  lr: 0.003333  max mem: 12016
2020-04-13 03:33:09,377 maskrcnn_benchmark.trainer INFO: eta: 3:51:23  iter: 160  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8016 (20.4462)  loss_mask: 0.6813 (0.8464)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5765 (1.5705)  data: 0.0199 (0.0248)  lr: 0.003333  max mem: 12016
2020-04-13 03:33:40,521 maskrcnn_benchmark.trainer INFO: eta: 3:50:38  iter: 180  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.7469 (20.4818)  loss_mask: 0.6839 (0.8283)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5736 (1.5690)  data: 0.0184 (0.0242)  lr: 0.003333  max mem: 12016
2020-04-13 03:34:12,061 maskrcnn_benchmark.trainer INFO: eta: 3:50:14  iter: 200  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.7912 (20.5148)  loss_mask: 0.6782 (0.8134)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5772 (1.5698)  data: 0.0197 (0.0237)  lr: 0.003333  max mem: 12016
2020-04-13 03:34:43,351 maskrcnn_benchmark.trainer INFO: eta: 3:49:38  iter: 220  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.7938 (20.5421)  loss_mask: 0.6792 (0.8013)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5785 (1.5693)  data: 0.0194 (0.0234)  lr: 0.003333  max mem: 12016
2020-04-13 03:35:14,519 maskrcnn_benchmark.trainer INFO: eta: 3:48:59  iter: 240  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8296 (20.5646)  loss_mask: 0.6777 (0.7912)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5752 (1.5684)  data: 0.0177 (0.0229)  lr: 0.003333  max mem: 12016
2020-04-13 03:35:46,076 maskrcnn_benchmark.trainer INFO: eta: 3:48:34  iter: 260  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8023 (20.5811)  loss_mask: 0.6815 (0.7827)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5786 (1.5692)  data: 0.0183 (0.0226)  lr: 0.003333  max mem: 12016``
`2020-04-13 04:42:32,096 maskrcnn_benchmark.trainer INFO: eta: 2:41:13  iter: 2820  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.7931 (20.7801)  loss_mask: 0.5795 (0.6331)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5750 (1.5652)  data: 0.0181 (0.0196)  lr: 0.010000  max mem: 12016
2020-04-13 04:43:03,630 maskrcnn_benchmark.trainer INFO: eta: 2:40:42  iter: 2840  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8526 (20.7803)  loss_mask: 0.5769 (0.6328)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5773 (1.5653)  data: 0.0188 (0.0196)  lr: 0.010000  max mem: 12016
2020-04-13 04:43:34,802 maskrcnn_benchmark.trainer INFO: eta: 2:40:10  iter: 2860  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.7914 (20.7804)  loss_mask: 0.5852 (0.6325)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5743 (1.5653)  data: 0.0196 (0.0196)  lr: 0.010000  max mem: 12016
2020-04-13 04:44:05,982 maskrcnn_benchmark.trainer INFO: eta: 2:39:39  iter: 2880  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8071 (20.7806)  loss_mask: 0.5795 (0.6321)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5751 (1.5652)  data: 0.0179 (0.0196)  lr: 0.010000  max mem: 12016
2020-04-13 04:44:37,220 maskrcnn_benchmark.trainer INFO: eta: 2:39:07  iter: 2900  loss: nan (nan)  loss_centerness: nan (nan)  loss_cls: 20.8334 (20.7808)  loss_mask: 0.5851 (0.6318)  loss_maskiou: nan (nan)  loss_reg: nan (nan)  time: 1.5772 (1.5652)  data: 0.0185 (0.0196)  lr: 0.010000  max mem: 12016
`
