### ISSUE TITLE
ERROR in coco_eval.py when runing test_net.py

### ISSUE THREAD

**Issue by sadik1111** [youngwanLEE/CenterMask#35]
@youngwanLEE 
When I tried to test the model, there are some touble fllow:
`Traceback (most recent call last):
  File "tools/test_net.py", line 97, in <module>
    main()
  File "tools/test_net.py", line 91, in main
    output_folder=output_folder,
  File "/home/sadik/CenterMask/maskrcnn_benchmark/engine/inference.py", line 117, in inference
    **extra_args)
  File "/home/sadik/CenterMask/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 22, in evaluate
    return coco_evaluation(**args)
  File "/home/sadik/CenterMask/maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py", line 20, in coco_evaluation
    expected_results_sigma_tol=expected_results_sigma_tol,
  File "/home/sadik/CenterMask/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 44, in do_coco_evaluation
    coco_results["bbox"] = prepare_for_coco_detection(predictions, dataset)
  File "/home/sadik/CenterMask/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 75, in prepare_for_coco_detection
    if len(prediction) == 0:
TypeError: object of type 'int' has no len()`
I tried to convert `prediction` to list, but it is obviously wrong.Thank for any help

**Comment by sadik1111** [comment]
### Environment
Versions of relevant libraries:
[pip] numpy==1.18.2
[pip] torch==1.1.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.2.2                     <pip>
        Pillow (6.2.0)
