### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by YueZhang1029** [youngwanLEE/CenterMask#40]
Hi,when i try to run demo/webcam.py i get the error
_pickle.UnpicklingError: pickle data was truncated

Here is the full result:
Traceback (most recent call last):
  File "webcam.py", line 80, in <module>
    main()
  File "webcam.py", line 64, in main
    min_image_size=args.min_image_size,
  File "D:\Project\CenterMask-master\demo\predictor.py", line 159, in __init__
    _ = checkpointer.load(cfg.MODEL.WEIGHT)
  File "d:\project\centermask-master\maskrcnn_benchmark\utils\checkpoint.py", line 62, in load
    checkpoint = self._load_file(f)
  File "d:\project\centermask-master\maskrcnn_benchmark\utils\checkpoint.py", line 138, in _load_file
    return load_c2_format(self.cfg, f)
  File "d:\project\centermask-master\maskrcnn_benchmark\utils\c2_model_loading.py", line 175, in load_c2_format
    return C2_FORMAT_LOADER[cfg.MODEL.BACKBONE.CONV_BODY](cfg, f)
  File "d:\project\centermask-master\maskrcnn_benchmark\utils\c2_model_loading.py", line 165, in load_resnet_c2_format
    state_dict = _load_c2_pickled_weights(f)
  File "d:\project\centermask-master\maskrcnn_benchmark\utils\c2_model_loading.py", line 136, in _load_c2_pickled_weights
    data = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: pickle data was truncated

**Comment by rohit7044** [comment]
Because you don't have enought RAM.
Also this [#5301](https://github.com/open-mmlab/mmdetection/issues/5301#issuecomment-1714836720)
Please close this issue.
Thanks

**Comment by rohit7044** [comment]
Also found out that proper CUDA version is also important
