### ISSUE TITLE
Runtime Error: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by sabine1993** [youngwanLEE/CenterMask#43]
Hi everyone,
I have a problem to rum the train_net script.
I followed the installations and everything worked fine. I want to train the model with coco dataset But I always get the runtime error. Did anyone has the same problem and can help me out?
Thanks a lot 

Bad key "text.kerning_factor" on line 4 in
C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "tools/train_net.py", line 196, in <module>
    main()
  File "tools/train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 88, in train
    arguments,
  File "c:\users\skugler\desktop\centermask\maskrcnn_benchmark\engine\trainer.py", line 83, in do_train
    loss_dict = model(images, targets)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\skugler\desktop\centermask\maskrcnn_benchmark\modeling\detector\generalized_rcnn.py", line 49, in forward
    features = self.backbone(images.tensors)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\skugler\desktop\centermask\maskrcnn_benchmark\modeling\backbone\mobilenet.py", line 115, in forward
    x = m(x)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\skugler\desktop\centermask\maskrcnn_benchmark\layers\misc.py", line 33, in forward
    return super(Conv2d, self).forward(x)
  File "C:\Users\skugler\AppData\Local\Continuum\anaconda3\envs\env_centermask\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by 007cat** [comment]
I meet the same problem today, have you solved it?
