### ISSUE TITLE
 fatal error: cpu/vision.h

### ISSUE THREAD

**Issue by ShellyLingling** [youngwanLEE/CenterMask#57]
Q1:  I only have four 2080TI graphics cards. Can I train on these?
Q2: When I tried to use Pytorch1.6, the following problems occurred:
python setup.py build develop
then

running build
running build_py
running build_ext
building 'maskrcnn_benchmark._C' extension
Emitting ninja build file /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/nms_cpu.o.d -pthread -B /home/zmb/anaconda3/envs/lyc/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Imaskrcnn_benchmark/csrc -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/TH -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zmb/anaconda3/envs/lyc/include/python3.7m -c -c /home/zmb/data/lyc/CenterMask/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp -o /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/nms_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/nms_cpu.o 
c++ -MMD -MF /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/nms_cpu.o.d -pthread -B /home/zmb/anaconda3/envs/lyc/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Imaskrcnn_benchmark/csrc -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/TH -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zmb/anaconda3/envs/lyc/include/python3.7m -c -c /home/zmb/data/lyc/CenterMask/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp -o /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/nms_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
**/home/z/CenterMask/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp:2:10: fatal error: cpu/vision.h: No such file or directory**
 #include "cpu/vision.h"
          ^~~~~~~~~~~~~~
compilation terminated.
[2/2] c++ -MMD -MF /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o.d -pthread -B /home/zmb/anaconda3/envs/lyc/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Imaskrcnn_benchmark/csrc -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/TH -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zmb/anaconda3/envs/lyc/include/python3.7m -c -c /home/zmb/data/lyc/CenterMask/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp -o /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o 
c++ -MMD -MF /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o.d -pthread -B /home/zmb/anaconda3/envs/lyc/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Imaskrcnn_benchmark/csrc -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/TH -I/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zmb/anaconda3/envs/lyc/include/python3.7m -c -c /home/zmb/data/lyc/CenterMask/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp -o /home/zmb/data/lyc/CenterMask/build/temp.linux-x86_64-3.7/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
**/home/z/CenterMask/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:2:10: fatal error: cpu/vision.h: No such file or directory**
 #include "cpu/vision.h"
          ^~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/zmb/anaconda3/envs/lyc/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by ShellyLingling** [comment]
I can train on two 2080TI graphics cards.
The second question didn't come up after I switched to centermask2.
